//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaliztionCRUD.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileWarehouseEntities : DbContext
    {
        public MobileWarehouseEntities()
            : base("name=MobileWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RisorseLocalizzazioneLabel> RisorseLocalizzazioneLabel { get; set; }
        public virtual DbSet<RisorseLocalizzazioneMessage> RisorseLocalizzazioneMessage { get; set; }
    }
}
