//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaliztionCRUD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RisorseLocalizzazioneLabel
    {
        public int idModulo { get; set; }
        public string labelFor { get; set; }
        public string lingua { get; set; }
        public string label { get; set; }
    }
}
